### ISSUE TITLE
Unable to use my own uploaded files

### ISSUE THREAD

**Issue by deeomnjobs** [xlang-ai/OpenAgents#101]
Unable to use my own uploaded files.
![image](https://github.com/xlang-ai/OpenAgents/assets/114485859/12566271-0ceb-40bc-9666-bce4b4b1524c)

**Comment by Timothyxxx** [comment]
That's because we have reached our quota for openai service, we have increased it to see if it can work.

**Comment by BlankCheng** [comment]
Hi, could you try it again with a smaller one?  I've tested it okay.

**Comment by deeomnjobs** [comment]
> Hi, could you try it again with a smaller one? I've tested it okay now.

It still doesn't work.
[Course.csv](https://github.com/xlang-ai/OpenAgents/files/13468872/Course.csv)

**Comment by BlankCheng** [comment]
I see. "Uploading" can work while "applying" it to the conversation fails in your case. It is because the file can't be decoded in utf-8.
We will try looking into that. You might also want to try other .csv which can work mostly.

**Comment by deeomnjobs** [comment]
> I see. "Uploading" can work while "applying" it to the conversation fails in your case. It is because the file can't be decoded in utf-8. We will try looking into that. You might also want to try other .csv which can work mostly.

thx
