### ISSUE TITLE
How to change the port of the frontend to call the backend

### ISSUE THREAD

**Issue by deeomnjobs** [xlang-ai/OpenAgents#103]
Since port 8000 is already taken in my own server, I deployed the backend on port 5093, but the frontend is still sending requests to port 8000. I was wondering where to change the request port for the frontend

**Comment by go-laoji** [comment]
https://github.com/xlang-ai/OpenAgents/blob/1a2091412a913a50a65d1bfba0ed33335d18d11f/frontend/utils/app/const.ts#L9-L10

you can set env `NEXT_PUBLIC_BACKEND_ENDPOINT` or change the line 10
