### ISSUE TITLE
frontend error: Failed to fetch

### ISSUE THREAD

**Issue by Xinyi118** [xlang-ai/OpenAgents#106]
backend and frontend installed in one system; system is Ubuntu 20.04. 

Backend start:
(base) root@iv-yctemf1w5c8lu7izhe3p:~/OpenAgents# flask run -p 8000
Dependencies for InstructorEmbedding not found. The auto selection feature of plugins agent will return random elements.
 75%|██████████████████████████████████████████████████████████▌                   | 12/16 [00:03<00:00,  5.95it/s]/root/OpenAgents/real_agents/plugins_agent/plugins/DreamInterpreter/openapi.yaml and DreamInterpreter/paths/__init__.py do not match. Load the later.
/root/OpenAgents/real_agents/plugins_agent/plugins/XWeather/openapi.yaml and XWeather/paths/__init__.py do not match. Load the later.
100%|██████████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.07it/s]
 * Serving Flask app 'backend.main.py'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8000
Press CTRL+C to quit

frontend start:
(base) root@iv-yctemf1w5c8lu7izhe3p:~/OpenAgents/frontend# npm run dev

> ai-chatbot-starter@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 3s (273 modules)
wait  - compiling...
event - compiled successfully in 235 ms (235 modules)
wait  - compiling / (client and server)...

event - compiled client and server successfully in 27.1s (20963 modules)

when open the browers, it show "Failed to fetch","Error getting conversation list!" , "Error getting LLM list!
" ,and can't upload any files (Network error occurred![object Object]
)

how can i fix

**Comment by Xinyi118** [comment]
any help?

**Comment by liangpn** [comment]
I've encountered the same error. How can I resolve it?
