### ISSUE TITLE
[BUG] Deleted file cannot be uploaded again

### ISSUE THREAD

**Issue by jayden222** [xlang-ai/OpenAgents#109]
After I delete a file in the uploaded files, I try to upload a modified file with the same name, but nothing happens. It seems that the `fileInputRef.current.files` did not clear successfully, as below.
![image](https://github.com/xlang-ai/OpenAgents/assets/29777487/024cd5e7-bf11-4231-9562-b8dce8b35552)

I am not familiar with the frontend code, please review for the bug. Thanks a lot.

**Comment by jayden222** [comment]
Is this repo still maintained?

**Comment by BlankCheng** [comment]
I think files with the same names are not to be overridden now. This might be the issue you met. Please check @WhiteWolf82
