### ISSUE TITLE
how to connect app with sql DB?

### ISSUE THREAD

**Issue by jim123ture** [xlang-ai/OpenAgents#111]
Is there any way to connect XLANG with SQL DB, such as local PC mySQL?

**Comment by BlankCheng** [comment]
Hi, for the online demo, there's no direct connection to MySQL. However, it is supported if you upload .sqlite and .db files.
For the localhost, the default backend data storage app is MongoDB, while you can feel free to add your own; and we deeply welcome any contribution to new database connections!
