### ISSUE TITLE
how to extend a new llm for the agent?

### ISSUE THREAD

**Issue by jackgreen12345** [xlang-ai/OpenAgents#113]
Noted that we can extend a hosted model whose format is similar with GPT4 conveniently, how can i extend a new llm which is 
quite different with GPT4? Is there any tutorials that can help me with extending a different llm?

**Comment by Timothyxxx** [comment]
Hi, thanks for the question, please check https://github.com/xlang-ai/OpenAgents?tab=readme-ov-file#extend-a-new-llm
