### ISSUE TITLE
Is there something works like session_id or user_id?

### ISSUE THREAD

**Issue by QixuanAI** [xlang-ai/OpenAgents#115]
I'm trying to save the session context on the self-hosted LLM server, but I don't know how to figure out which user/session is going on when OpenAgent is calling LLM's APIs. Is there something works like session_id or user_id?

I found a field names `llm_call_id` in `AgentStreamingStdOutCallbackHandler` of agent_streaming.py, but I'm not sure if it can works as I wish. 

If it is, can I visit this variable in function `_agenerate` from `run_manager.llm_call_id`?
Or any other advices, please?

**Comment by BlankCheng** [comment]
Hi, all conversations are saved in mongodb, including keys like `conversation_id` and `user_id`. If you succeed in localhosting OpenAgents project, mongodb should work and you could just check the database content.

I think `conversation_id` and `user_id` match the `session_id` and `user_id ' you need. Please feel free to follow up if it does not solve your problem.
