### ISSUE TITLE
This drawing is really nice. What app did you use to draw it?

### ISSUE THREAD

**Issue by ljch2018** [xlang-ai/OpenAgents#123]
https://github.com/xlang-ai/OpenAgents/blob/main/pics/data_agent.png

Thank you.

**Comment by Timothyxxx** [comment]
Thanks for your question, we used https://excalidraw.com/ to draw them

**Comment by ljch2018** [comment]
Thank you for your help.Would you please share the source file of this drawing? Thank you very much.
