### ISSUE TITLE
Demo website sign in stall. 

### ISSUE THREAD

**Issue by haddadnidal** [xlang-ai/OpenAgents#137]
when accessing the demo through your website the sign in does not go through i have CORS issues. 

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.xlang.ai/auth/login. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 522.` 

` Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. `

**Comment by Timothyxxx** [comment]
Thanks for your question. The demo website is down because of running out of funding about this project. Please deploy by yourself if you are interested, thanks!
