### ISSUE TITLE
Docker images

### ISSUE THREAD

**Issue by luisalrp** [xlang-ai/OpenAgents#15]
Hi!

Great project! Are you considering to dockerize it and build images on dockerhub or github container registry? Thanks!

**Comment by Timothyxxx** [comment]
Thanks for your attention and advice, we are planning to add that later on

**Comment by BlankCheng** [comment]
And if you want to take part in dockerizing the platform, just let us know in advance😄

**Comment by go-laoji** [comment]
I have implemented application orchestration using docker compose. Can I submit a PR?

**Comment by BlankCheng** [comment]
Welcome! That's so cool. Just submit a PR and briefly describe your implementations if possible. And we can discuss more details there.

**Comment by luisalrp** [comment]
@BlankCheng, I can do the github action to build and upload to ghcr the image

**Comment by sxflynn** [comment]
Is there an update on this? I am searching for docker-related good first issues and it seems this issue should be closed?
