### ISSUE TITLE
Failed to login with Google on the online demo.

### ISSUE THREAD

**Issue by youralmight** [xlang-ai/OpenAgents#25]
Expected: login with Google.
Actual: After I clicked "Continue with Google", chose the account to login with, and come back to the login page, the page is stuck on logging in with the waiting icon (the circle spinning).
![image](https://github.com/xlang-ai/OpenAgents/assets/42952005/1668022a-30d8-4d52-aac2-5b192314916c)

I opened developer tools to check the errors and found some CORS policy error.
![image](https://github.com/xlang-ai/OpenAgents/assets/42952005/49095ccf-8bde-4c0e-9b92-8353282c0ac8)

**Comment by Timothyxxx** [comment]
Hi, thanks for noting, we reboot and fix it, please try again!

**Comment by MMagicLoren** [comment]
I've got the same problem.

**Comment by surmount1** [comment]
I've also encountered this problem.

**Comment by BlankCheng** [comment]
Closed as the server is running now. More about demo can be discussed in discord.
