### ISSUE TITLE
why can't connect to the openai,show me the error Internal server error. Please try again.

### ISSUE THREAD

**Issue by hugenshen** [xlang-ai/OpenAgents#30]
POST  https://api.xlang.ai/api/chat
chat_id: "653932ea61e242a5c16c529e"
response：
{"success": false, "error": "internal", "error_msg": "Internal server error. Please try again."}

how can i fix it?

**Comment by Timothyxxx** [comment]
Thanks for your feedback! Please re-login to double-check if it is okay now.

**Comment by BlankCheng** [comment]
Closed as the demo is online now. More about demo can be discussed in discord!
