### ISSUE TITLE
flask run -p 8000, it gives error

### ISSUE THREAD

**Issue by liuchenbaidu** [xlang-ai/OpenAgents#36]

**Comment by liuchenbaidu** [comment]
Error when loading plugin KLARNA: [Errno 13] Permission denied: '/tmp/data-gym-cache/9b5ad71b2ce5302211f9c61530b329a4922fc6a4.7da17318-86d5-4b41-b140-25b929124057.tmp'
  6%|█████████▌                                                                                                                                              | 1/16 [00:02<00:42,  2.82s/it]Error when loading plugin ZAPIER: [Errno 13] Permission denied: '/tmp/data-gym-cache/9b5ad71b2ce5302211f9c61530b329a4922fc6a4.54340a96-f791-48c1-ae7b-70c95b6e973b.tmp'
 12%|███████████████████                                                                                                                                     | 2/16 [00:05<00:36,  2.62s/it]Error when loading plugin COURSERA: [Errno 13] Permission denied: '/tmp/data-gym-cache/9b5ad71b2ce5302211f9c61530b329a4922fc6a4.62a58191-fe5b-4da6-bb8e-1dff77332eea.tmp'
 19%|████████████████████████████▌                                                                                                                           | 3/16 [00:07<00:33,  2.55s/it]Error when loading plugin JOBSEARCH: [Errno 13] Permission denied:

**Comment by Timothyxxx** [comment]
Hi, it may due to the error from `tiktoken`, since we use `titoken` to count the tokens to fit into the LLMs, check this issue please https://github.com/openai/tiktoken/issues/75 .

**Comment by BlankCheng** [comment]
Closed as the issues suspends for long. Please reopen if there's any further problem.
