### ISSUE TITLE
Open source Base LLM for Agent?

### ISSUE THREAD

**Issue by astarostap** [xlang-ai/OpenAgents#44]
has anyone tried using open source LLMs to power the agent? if so which ones worked? and what's the difference in quality vs GPT4 vs GPT3.5 vs Claude.

**Comment by BlankCheng** [comment]
We have a tutorial for LLM/agent/tool extension in the README. Hope that helps you.

**Comment by BlankCheng** [comment]
Closed as no further discussion. Please feel free to reopen it if needed.
