### ISSUE TITLE
在执行flask run -p 8000时遇到这个，进去以后404

### ISSUE THREAD

**Issue by iaoxuesheng** [xlang-ai/OpenAgents#52]
![微信图片_20231030225108](https://github.com/xlang-ai/OpenAgents/assets/94165844/2a421ad8-d7cf-4766-9927-957fc9de333f)
在执行flask run -p 8000时遇到这个错误，不知道什么意思，进去以后404，但是好像最终的可以连接到openagents,好像不太影响使用，想问一下这个是什么意思。

**Comment by BlankCheng** [comment]
现在可以访问localhost:3000的前端吗？

**Comment by iaoxuesheng** [comment]
可以访问，就是那个端口号8000的访问不了

**Comment by BlankCheng** [comment]
`flask run -h 0.0.0.0 -p 8000` 设置一下host可以吗

**Comment by iaoxuesheng** [comment]
也是一样的

**Comment by QIN2DIM** [comment]
你说的“这个错误”指的是什么 @iaoxuesheng

**Comment by iaoxuesheng** [comment]
> 你说的“这个错误”指的是什么 @iaoxuesheng

@QIN2DIM 里面报了一个error

**Comment by mendynew** [comment]
一样的错误。最后是怎么使用的呢？为何说不影响使用啊

**Comment by iaoxuesheng** [comment]
> 一样的错误。最后是怎么使用的呢？为何说不影响使用啊

最后前端正常启动使用啊，能连接gpt3.5实现Data agent

**Comment by BlankCheng** [comment]
Closed as inactive. Please feel free to reopen it if you meet any problems.
