### ISSUE TITLE
pdfjs 编译出错, node已经退到18.6.0

### ISSUE THREAD

**Issue by xjq284** [xlang-ai/OpenAgents#54]
Server Error
TypeError: Cannot read properties of undefined (reading 'includes')

This error happened while generating the page. Any console logs will be displayed in the terminal window.

**Comment by BlankCheng** [comment]
We have removed pdfjs dependency now. Could you try it again?

**Comment by BlankCheng** [comment]
Closed as no further discussion. Please feel free to reopen it if needed.
