### ISSUE TITLE
csv path not right - file cannot be found

### ISSUE THREAD

**Issue by harrywang** [xlang-ai/OpenAgents#57]
I used the kaggle plugin to download a csv file as shown below. The data profiling shows the correct results:
<img width="2494" alt="Screenshot 2023-10-31 at 6 26 21 PM" src="https://github.com/xlang-ai/OpenAgents/assets/595772/57174116-f546-4908-84b6-39d9e9db3607">

However, when I want to visualize the data, the code seems to be correct but the file path is not correct:

<img width="2516" alt="Screenshot 2023-10-31 at 6 24 01 PM" src="https://github.com/xlang-ai/OpenAgents/assets/595772/4993fd1f-7402-4518-8f07-29af3bbbee46">

I don't know how to change the path to reflect the folder structure shown on the left - please help.

Thanks!

**Comment by go-laoji** [comment]
if you run the code in sandbox with docker,you shoud mout 
`ource=<PATH_TO_PROJECT>/backend/data,target=/home`

**Comment by harrywang** [comment]
> if you run the code in sandbox with docker,you shoud mout `source=<PATH_TO_PROJECT>/backend/data,target=/home`

Thanks, my screenshots were made at https://chat.xlang.ai/ - not local

**Comment by harrywang** [comment]
> if you run the code in sandbox with docker,you shoud mout `source=<PATH_TO_PROJECT>/backend/data,target=/home`

we have tried this and it seems to solve the problem - thanks!
