### ISSUE TITLE
No such file or directory:'backend/static/images/SQLQueryBuilder.cache'

### ISSUE THREAD

**Issue by unique-Li-yuankun** [xlang-ai/OpenAgents#6]
When I post to /api/data_tool_list     
an error occur.
Has anyone meet this ,how to solve this?

![image](https://github.com/xlang-ai/OpenAgents/assets/58254161/09bc46fc-c5f0-4faf-9351-28ae601c6ef1)
This is my /backend/static/images   directory
![image](https://github.com/xlang-ai/OpenAgents/assets/58254161/7c49f8f6-312a-4846-bd61-8ebe73bb1354)

**Comment by Timothyxxx** [comment]
Sorry for the missing, we will check and upload asap

**Comment by BlankCheng** [comment]
Hi, I've updated the cache files. You can check it out and let us know if it doesn't go well.

**Comment by unique-Li-yuankun** [comment]
It works ,but need to copy the cache files from /backend/static/ to backend/static/images/ directory manually.
Thank you very much for your quick reply and quick upload.

**Comment by BlankCheng** [comment]
Glad it helps! And I have moved them to the `backend/static/images` now.
