### ISSUE TITLE
unnecessary agent adapter and helpers

### ISSUE THREAD

**Issue by Jeffwan** [xlang-ai/OpenAgents#61]
I am checking the code and notice some code under `adapter/agent_helpers` are very similar to langchain implementation (like `AgentOutputParser`, `Agent` etc). I am curious are these helper necessary? would it be possible to build them directly using langchain package? 

Could you share some thoughts to create that share library between agents? What's the limitation of langchain to implement your agent?

**Comment by BlankCheng** [comment]
Hi, you are right. As described in our paper, the adapters are used to "adapt language agent to real agent in application". 
We follow Langchain in language agent implementation while modifying some parts to assist the application to be robust, such as truncation, streaming, and other issues discussed in paper Section3.2.
Back to your problem, some files are modified slightly by copying Langchain files and making what we want which pure Langchain package doesn't support. But they are necessary to the platform's performance.

**Comment by Jeffwan** [comment]
@BlankCheng Thank you. I will read the paper carefully and catch the part you mentioned. Thanks for the explaination.
