### ISSUE TITLE
fail to use the tool since tool selection is inaccurate

### ISSUE THREAD

**Issue by Jeffwan** [xlang-ai/OpenAgents#69]
I am trying to use EChart tool to draw a plot. However, I feel it's really hard..
It tries to write echarts tool in python but not adopt the tool directly..

![image](https://github.com/xlang-ai/OpenAgents/assets/4739316/66a53c50-84d9-4e8a-97ad-d77faefb9583)

![image](https://github.com/xlang-ai/OpenAgents/assets/4739316/72e0c9b0-5c28-4255-8b95-7c345428dc7c)

![image](https://github.com/xlang-ai/OpenAgents/assets/4739316/a46be1ae-a233-4188-a643-d2cccf589bc6)

![image](https://github.com/xlang-ai/OpenAgents/assets/4739316/9a8f5f69-5fd7-45bd-bc70-1e097995b4f0)

**Comment by Timothyxxx** [comment]
Thanks for your question, the same reason as https://github.com/xlang-ai/OpenAgents/issues/67 ~

**Comment by Jeffwan** [comment]
@Timothyxxx Thanks! I will switch to GPT-4 and give it another try. I will close this issue and let's track the problem in #67
