### ISSUE TITLE
What if I want to use the registration and login feature when I deploy locally?

### ISSUE THREAD

**Issue by mzxhzhp** [xlang-ai/OpenAgents#73]
When I access https://chat.xlang.ai, it displays a login page saying "Welcome to XLANG" and asks me to choose between logging in with a Google account or email. 
However, when I deploy OpenAgents locally and access http://xxx.xxx.xxx.xxx:xxxx in the browser, it doesn't show a login or registration page but directly enters the chat interaction page using the default account DEFAULT_USER_ID. Moreover, I only see the definition of the API_REGISTER_USER variable in the frontend/ directory, but I couldn't find where it is being called. What is the underlying principle behind this?

If I want to enable the registration and login functionality during local deployment, how can I modify it? I'm not familiar with the frontend, is there any friend can point out, thank you very much.

**Comment by mzxhzhp** [comment]
In the handleSend function in OpenAgents/frontend/pages/api/home/home.tsx, before making a POST request to the backend "/api/chat_xlang_plugin", the message body is being packaged, which includes fields such as user_intent, chat_id, and parent_message_id. However, it seems that the user_id is missing. How should we understand this?
If that's the case, then in OpenAgents/backend/api/chat_plugin.py, won't the user_id always be set to DEFAULT_USER_ID?

**Comment by mzxhzhp** [comment]
I accidentally clicked 'close' above, sorry.

**Comment by mzxhzhp** [comment]
I accidentally clicked 'close' above, sorry.

**Comment by BlankCheng** [comment]
Hi, we are sorry the demo is down now. We are considering moving it to a smaller and cheaper server these days.
Btw, welcome to our discord server where we discuss everything about the online demo.

**Comment by BlankCheng** [comment]
Maybe @WhiteWolf82 can give some instructions about adding a user system.

**Comment by WhiteWolf82** [comment]
Hi @mzxhzhp , thank you for your interest for our project. We disabled the entire user system and the corresponding code to maintain a minimum open-sourced version. We believed it was the best option because a fully-functioned user system involve many bussiness logic, which maybe unwanted by researchers.

If you want to add a user system, you should follow instructions online to implement the standard register & login features, which I believe there are many resources for reference. And always check for autheication in http requests, like sending messages, uploading files, etc.

**Comment by mzxhzhp** [comment]
> Hi @mzxhzhp , thank you for your interest for our project. We disabled the entire user system and the corresponding code to maintain a minimum open-sourced version. We believed it was the best option because a fully-functioned user system involve many bussiness logic, which maybe unwanted by researchers.
> 
> If you want to add a user system, you should follow instructions online to implement the standard register & login features, which I believe there are many resources for reference. And always check for autheication in http requests, like sending messages, uploading files, etc.

Thank you for your patient explanation.   I finally understand.   
Actually, my biggest confusion was why I couldn't see the code logic behind the effects demonstrated in the demo from the source code.   I wondered if I missed something or didn't understand it correctly.   Confusion has always been my greatest enemy, and if I can't figure things out, it feels like there are thousands of ants crawling in my heart.   I also speculated that the open-source code might not include everything shown in the demo, but it was just a guess.   Now that I have your confirmation, I finally feel relieved.   Thank you once again.
