### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by miandai** [xlang-ai/OpenAgents#76]
When I access http://localhost:3000/zh. An error occurred：TypeError: Cannot read properties of undefined (reading 'map')

<img width="962" alt="image" src="https://github.com/xlang-ai/OpenAgents/assets/4371622/f6e8d374-ca52-454d-8125-1040ab18feea">

os：mac
npm：8.15.0
node：v18.7.0

**Comment by BlankCheng** [comment]
Closed as inactive. Please feel free to reopen it if you meet any problems.
