### ISSUE TITLE
flash run -p 8000运行报错

### ISSUE THREAD

**Issue by liuteng1988** [xlang-ai/OpenAgents#77]
Error: While importing 'backend.main', an ImportError was raised:
Import padas._libs.window.aggregations as window_aggregations
libstdc++.so.6:version 'GLIBCXX_3.4.29'not found

**Comment by Timothyxxx** [comment]
Thanks for your question! 

This printout seems weird, we never met this issue before.

**Comment by Timothyxxx** [comment]
Could you first try on the solutions provided [here](https://stackoverflow.com/questions/60763529/unable-to-import-pandas-pandas-libs-window-aggregations)?

**Comment by BlankCheng** [comment]
Closed as inactive. Please feel free to reopen it if you meet any problems.
