### ISSUE TITLE
No such file or directory: 'backend/data/DefaultUser

### ISSUE THREAD

**Issue by SovereignRemedy** [xlang-ai/OpenAgents#81]
exec python code 
output such as 

`<output>
[ERROR]: [Errno 2] No such file or directory: 'backend/data/DefaultUser
</output>`

![image](https://github.com/xlang-ai/OpenAgents/assets/23444367/f124b910-03f8-4eb3-8baf-5b4821e8d90c)

**Comment by Timothyxxx** [comment]
Thanks for your question, is this an error that happened in online demo or self-hosted?

**Comment by SovereignRemedy** [comment]
> Thanks for your question, is this an error that happened in online demo or self-hosted?

I deployed the service locally, and I found through Debug that he seems to be in  “python_evaluator.py” line 97 
`os.chdir(os.path.join("backend/data/", user_id))`.
If I comment out this line, the next ipython executor will report an error that the uploaded file cannot be found

ide file
![image](https://github.com/xlang-ai/OpenAgents/assets/23444367/e8cdb683-f7f1-4c0f-8f1f-024d1713ec07)


log
`2023-11-08 12:50:21 | TRACE - ++-> PythonChain generated program:
import pandas as pd

# Read the CSV file
df = pd.read_csv('0d6ae2295f7046dc964fe846a425bd53.csv')

# Filter the data for the specified building
building_df = df[df['名称'] == 'xxx']

column = building_df['xxx']

# Convert the column to a list
list = column.tolist()

# Print the list
print(list)`

`FileNotFoundError: [Errno 2] No such file or directory: '0d6ae2295f7046dc964fe846a425bd53.csv'`

**Comment by SovereignRemedy** [comment]
It's very strange that we haven't been able to implement it in the morning and now we can try to put the problem on hold

**Comment by SovereignRemedy** [comment]
It's okay to try again. Maybe it's my local environment

**Comment by BlankCheng** [comment]
Hi, the path code can't be commented.  Are you trying to host from docker? If so, you may have to mount the data path `source=<PATH_TO_PROJECT>/backend/data,target=/home`.
