### ISSUE TITLE
config front server

### ISSUE THREAD

**Issue by jokerjoey** [xlang-ai/OpenAgents#82]
I deplyed front and backend on different servers. How I can config backend server ip address in frontend?
It seems user also needs a user_id to access backend server, how can I generate it?

**Comment by jokerjoey** [comment]
BTW, I need to use azure openai. I have modified language_model.py in backend.
But the deploymennt_id doesn't equal model name, is only put my deployment_id in that python file ok?

**Comment by go-laoji** [comment]
you need config env for `NEXT_PUBLIC_BACKEND_ENDPOINT` befor build frontend

**Comment by jokerjoey** [comment]
HI @go-laoji Thanks for your reply. I have put this in .env. But seems frontend can't connect to backend, it shows connect refused.
I checked backend code, seems it need user_id, where can I generate this?

**Comment by go-laoji** [comment]
Tue user_id has default value.  It's `DefaultUser`
