### ISSUE TITLE
'backend overloaded'

### ISSUE THREAD

**Issue by Captain-Bacon** [xlang-ai/OpenAgents#83]
I follow the instructions to set up a local version of OpenAgents
-conda env
-front-end npm
-back-end docker
-embeddings repo
-edit the .yaml to add my openai_api_key ( I assume it should be enclosed in " ", but I've tried it both ways, just in case)
-export all the things
-docker build
-docker compose

I can get the frontend running, but no matter what I do I always get a 'backend overloaded' error

I'm running an M2 Max Macbook

Would love to get this running!

**Comment by AllenJShi** [comment]
Same issue here, I was not able to use it even if I entered my api key. Wonder if there is a solution to that

**Comment by Enogh** [comment]
I'm in the same situation

**Comment by BlankCheng** [comment]
@go-laoji Can you check the setup issue of docker?

**Comment by Enogh** [comment]
How is this check done?

**Comment by Enogh** [comment]
@go-laoji  No, I am working on Windows operating system. But I got so many errors that I lost faith in openagents being a workable thing. When I use the data analysis agent in my installation with Docker, an error occurs in the Openai version, and a "backend overloaded" error occurs in the plug-in agent. Flask gives many errors when installed with Python 3.11. Frankly, I was able to do the safest installation with docker, but I think the docker installation documents and files are not complete, I will try again today, starting from the beginning.

**Comment by Enogh** [comment]
@go-laoji  Docker is the easiest and most error-free installation option, but there are errors regarding the versions of the libraries used, and the documents for additional installations such as the plug-in agent and web agent need to be re-examined in the installation documentation with Docker. I have used many agents and openagents seems to be the best, but I noticed that everyone experienced many errors during installation. This problem needs to be eliminated.

**Comment by Enogh** [comment]
The error has been resolved. This error occurs when the "auto" option is selected in the plug-in agent. The openai error has been fixed in the repository. If the repository is reinstalled and installed, the error will be resolved. However, the auto plug-in cannot be used.

**Comment by BlankCheng** [comment]
Hi, could you try the lastest docker file and code to see whether the auto selection works since @go-laoji fixed it in #98
