### ISSUE TITLE
docker run error

### ISSUE THREAD

**Issue by shanmu-raoyunfei** [xlang-ai/OpenAgents#84]
docker run error：

<img width="1679" alt="image" src="https://github.com/xlang-ai/OpenAgents/assets/144103401/b928d130-1a50-4691-9d30-2dbea2148fa0">

**Comment by ztjhz** [comment]
Did you use the docker compose script? What's the error you see in the terminal and the browser console?

**Comment by shanmu-raoyunfei** [comment]
> Did you use the docker compose script? What's the error you see in the terminal and the browser console?

yes。i use the docker compose script，and docker error：

openagents-backend-1           | AI: 
openagents-backend-1           | ================</prompt>================
openagents-backend-1           | 
openagents-mongodb-1           | {"t":{"$date":"2023-11-18T10:36:28.789+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.24.0.5:49186","uuid":{"uuid":{"$uuid":"ef089d7f-3175-42b0-b833-8d5a3155c4c7"}},"connectionId":14,"connectionCount":7}}
openagents-mongodb-1           | {"t":{"$date":"2023-11-18T10:36:28.790+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn14","msg":"client metadata","attr":{"remote":"172.24.0.5:49186","client":"conn14","doc":{"driver":{"name":"PyMongo","version":"4.3.3"},"os":{"type":"Linux","name":"Linux","architecture":"aarch64","version":"6.4.16-linuxkit"},"platform":"CPython 3.10.4.final.0"}}}
openagents-backend-1           | Traceback (most recent call last):
openagents-backend-1           |   File "/app/backend/utils/streaming.py", line 165, in _wrap_agent_caller
openagents-backend-1           |     _ = interaction_executor(inputs, callbacks=callbacks)
openagents-backend-1           |   File "/usr/local/lib/python3.10/site-packages/langchain/chains/base.py", line 140, in __call__
openagents-backend-1           |     raise e
openagents-backend-1           |   File "/usr/local/lib/python3.10/site-packages/langchain/chains/base.py", line 134, in __call__
openagents-backend-1           |     self._call(inputs, run_manager=run_manager)
openagents-backend-1           |   File "/app/real_agents/adapters/agent_helpers/agent.py", line 620, in _call
openagents-backend-1           |     next_step_output = self._take_next_step(
openagents-backend-1           |   File "/app/real_agents/adapters/agent_helpers/agent.py", line 532, in _take_next_step
openagents-backend-1           |     output = self.agent.plan(
openagents-backend-1           |   File "/app/real_agents/data_agent/copilot.py", line 165, in plan
openagents-backend-1           |     full_output = self.llm_chain.predict(callbacks=callbacks, **full_inputs)
openagents-backend-1           |   File "/app/real_agents/adapters/llm.py", line 210, in predict
openagents-backend-1           |     return self(kwargs, callbacks=callbacks)[self.output_key]
openagents-backend-1           |   File "/usr/local/lib/python3.10/site-packages/langchain/chains/base.py", line 140, in __call__
openagents-backend-1           |     raise e
openagents-backend-1           |   File "/usr/local/lib/python3.10/site-packages/langchain/chains/base.py", line 134, in __call__
openagents-backend-1           |     self._call(inputs, run_manager=run_manager)
openagents-backend-1           |   File "/app/real_agents/adapters/llm.py", line 73, in _call
openagents-backend-1           |     response = self.generate([inputs], run_manager=run_manager)
openagents-backend-1           |   File "/app/real_agents/adapters/llm.py", line 90, in generate
openagents-backend-1           |     return self.llm.generate_prompt(prompts, stop, callbacks=run_manager.get_child() if run_manager else None)
openagents-backend-1           |   File "/usr/local/lib/python3.10/site-packages/langchain/chat_models/base.py", line 143, in generate_prompt
openagents-backend-1           |     return self.generate(prompt_messages, stop=stop, callbacks=callbacks)
openagents-backend-1           |   File "/usr/local/lib/python3.10/site-packages/langchain/chat_models/base.py", line 91, in generate
openagents-backend-1           |     raise e
openagents-backend-1           |   File "/usr/local/lib/python3.10/site-packages/langchain/chat_models/base.py", line 83, in generate
openagents-backend-1           |     results = [
openagents-backend-1           |   File "/usr/local/lib/python3.10/site-packages/langchain/chat_models/base.py", line 84, in <listcomp>
openagents-backend-1           |     self._generate(m, stop=stop, run_manager=run_manager)
openagents-backend-1           |   File "/app/real_agents/adapters/models/openai.py", line 301, in _generate
openagents-backend-1           |     for stream_resp in self.completion_with_retry(messages=message_dicts,
openagents-backend-1           |   File "/app/real_agents/adapters/models/openai.py", line 248, in completion_with_retry
openagents-backend-1           |     retry_decorator = self._create_retry_decorator()
openagents-backend-1           |   File "/app/real_agents/adapters/models/openai.py", line 237, in _create_retry_decorator
openagents-backend-1           |     retry_if_exception_type(openai.error.Timeout)
openagents-backend-1           | AttributeError: module 'openai' has no attribute 'error'

I can confirm that openai is accessible。what's happen？
thks

**Comment by go-laoji** [comment]
did you config `OPENAI_API_BASE`
