### ISSUE TITLE
support for Azure OpenAI api 

### ISSUE THREAD

**Issue by georgehu0815** [xlang-ai/OpenAgents#85]
need support for Azure OpenAI  API

config_list = autogen.config_list_from_dotenv(
    dotenv_file_path='.env',
    model_api_key_map={
        "gpt-4": "OPENAI_API_KEY",
        "gpt-3.5-turbo": {
            **"api_key_env_var": "ANOTHER_API_KEY",
            "api_type": "aoai",
            "api_version": "v2",
            "base_url": "https://api.someotherapi.com"**
        }
    },
    filter_dict={
        "model": {
            "gpt-4",
            "gpt-3.5-turbo",
        }
    }
)

config_list

Reference:
https://github.com/microsoft/autogen/blob/main/notebook/oai_openai_utils.ipynb

**Comment by Timothyxxx** [comment]
Agree, we are going to add that later.

**Comment by ZuoVJ** [comment]
needed +1

**Comment by geniuszxd** [comment]
needed +1

**Comment by koalazf99** [comment]
solved in #117
