### ISSUE TITLE
What's the difference between 'real_agents/plugins_agent/plugin_prompt.py' and 'real_agents/plugins_agent/api_calling/prompt.py' ?

### ISSUE THREAD

**Issue by jayden222** [xlang-ai/OpenAgents#86]
I noticed that both prompts are used in the chat_plugin.py, but I didn't understand the different usage between them since they both required the LLM to generate selected plugin and input json.

**Comment by koalazf99** [comment]
Hi @jayden222 ! Good Question!

Actually, the agent has some kind of hierarchy architecture.

The prompt in `real_agents/plugins_agent/plugin_prompt.py` is the general prompt prepared for the Plugin Agent. 
Equipped with the plugin_prompt, the agent will thus be able to call the plugins via certain format. 
(👆actually like a task assigner, will decide when to call the plugin, and which plugin to call)

Meanwhile, the plugin is also driven by an LLM, which should handle and decide issues like: **_whether the returned results of API provider are satisfactory_**
The prompt in `real_agents/plugins_agent/api_calling/prompt.py` is thus to prompt another LLM to handle this single API calling. 
(👆actually like a task assignee, will work on the specific API calling)

**Comment by Timothyxxx** [comment]
Yes! That's the core problem, in academics we can it decomposition of questions. In a more fashion way, we can it high-level tasks and low-level tasks in a tool-usage agent.
