### ISSUE TITLE
运行flask run -p 8000后 加载到16/16后无反应

### ISSUE THREAD

**Issue by GuoXu-booo** [xlang-ai/OpenAgents#87]
Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/ai/.kaggle/kaggle.json'
Dependencies for InstructorEmbedding not found. The auto selection feature of plugins agent will return random elements.
 62%|██████████████████████████▉                | 10/16 [00:00<00:00, 30.85it/s]/data/Guo/OpenAgents-main/real_agents/plugins_agent/plugins/DreamInterpreter/openapi.yaml and DreamInterpreter/paths/__init__.py do not match. Load the later.
/data/Guo/OpenAgents-main/real_agents/plugins_agent/plugins/XWeather/openapi.yaml and XWeather/paths/__init__.py do not match. Load the later.
100%|███████████████████████████████████████████| 16/16 [00:00<00:00, 30.93it/s]

接着就长时间无响应，这是什么情况呢？

**Comment by duduxiao** [comment]
我本地也没有跑成功，你原因是需要科学上网，这里会访问www.wolframcdn.com。后面还有其他坑。

**Comment by Timothyxxx** [comment]
@GuoXu-booo @duduxiao 抱歉没考虑需要科学上网的问题，如果说任何需要帮助的地方欢迎随时提问！我们尽其所能修复
