### ISSUE TITLE
[ERROR]: name 'generate_continuous_elegant_python_code' is not defined

### ISSUE THREAD

**Issue by georgehu0815** [xlang-ai/OpenAgents#88]
<img width="1045" alt="image" src="https://github.com/xlang-ai/OpenAgents/assets/116222457/e8d53a0c-7f6b-4ed8-adb1-531a85005f21">

<img width="598" alt="image" src="https://github.com/xlang-ai/OpenAgents/assets/116222457/60feca28-1335-4a34-859f-cc94503470fd">

**Comment by georgehu0815** [comment]
AI: Your table E-commerce Customer Behavior - Sheet1 contains 350 rows and 11 columns. On average, each column has about 50 unique values. Watch out, there are 2 missing values in your data. 
Here are some additional insights to enhance your understanding of the table.
1. E-commerce behavior data by customers.
2. Analyze customer satisfaction, spending habits, and purchase history.
3. Identify correlations between customer demographics and spending.
Human: Analyze customer satisfaction, spending habits, and purchase history.
AI: ```json
{
    "action": "PythonCodeBuilder",
    "action_input": "calculate the average satisfaction level of each membership type",
}
```
[RESPONSE_BEGIN]
<code>
generate_continuous_elegant_python_code(history_dict)
</code>

<output>
[ERROR]: name 'generate_continuous_elegant_python_code' is not defined
</output>

**Comment by georgehu0815** [comment]
Observation: {
    "success": "False",
    "result": "[ERROR]: name 'generate_continuous_elegant_python_code' is not defined",
    "intermediate_steps": "generate_continuous_elegant_python_code(history_dict)"
}
Thought:

> Finished chain.

**Comment by Timothyxxx** [comment]
It seems like the agent encounters some trouble with the format, and I thought it maybe due to the fact you used the gpt-3.5 instead of gpt-4 which are less intelligent when considering the instruction following, would you mind changing the LLM and see if it helps?
