### ISSUE TITLE
Not able to run locally

### ISSUE THREAD

**Issue by AllenJShi** [xlang-ai/OpenAgents#89]
Hi, I ran into `backend overload` error while trying the plugin agent on my local. Can anyone let me know if there is a solution to that or did I build in a incorrect way?

**Comment by Timothyxxx** [comment]
Hi, sorry for the bothering you, we are discussing this issue in https://github.com/xlang-ai/OpenAgents/issues/83 , we will fix that very soon.

**Comment by BlankCheng** [comment]
Closed as fixed in #98 . Please feel free to reopen if you still meet this problem!
