### ISSUE TITLE
No such file or directory: 'backend/static/images/PythonCodeBuilder.cache'

### ISSUE THREAD

**Issue by skyrain888** [xlang-ai/OpenAgents#9]
运行后台启动后，进入页面后台报
No such file or directory: 'backend/static/images/PythonCodeBuilder.cache'
看了下文件
PythonCodeBuilder也不存在
Echarts也没有，
DATA_TOOLS应该没配置正确

**Comment by BlankCheng** [comment]
Hi, 我们昨天上传了一版新的cache文件，在`https://github.com/xlang-ai/OpenAgents/blob/main/backend/static/images/`。
可以再pull一次最新的代码看看能不能跑通？

**Comment by Timothyxxx** [comment]
Yes, please check out https://github.com/xlang-ai/OpenAgents/pull/7

**Comment by MikeyBeez** [comment]
Did you try touching the file?    touch backend/static . . .

**Comment by BlankCheng** [comment]
We haven’t heard back from you in a while, so I’m going to close this issue for now. If you’re still experiencing this problem, please feel free to reopen it or create a new issue. Thanks for your contribution!
