### ISSUE TITLE
Data/Plugin Agent not working

### ISSUE THREAD

**Issue by AllenJShi** [xlang-ai/OpenAgents#91]
I successfully ran app in docker. However, I was unable to use any agents. Data Agent never returned a word but at least it showed the conversation log. Plugin Agent always got into `backend is currently overloaded`. Wonder anyone successfully deployed the app?

**Comment by Timothyxxx** [comment]
Hi @AllenJShi , it seems to due to the docker and openai problems, we (@go-laoji , @Enogh) are working that, check here https://github.com/xlang-ai/OpenAgents/issues/83
