### ISSUE TITLE
Error: Failed to make the request MAPS

### ISSUE THREAD

**Issue by yuantony009** [xlang-ai/OpenAgents#92]
Dependencies for InstructorEmbedding not found. The auto selection feature of plugins agent will return random elements.
 62%|████████████████████████████████████████████▍                          | 10/16 [00:00<00:00, 20.38it/s]/root/OpenAgents-main/real_agents/plugins_agent/plugins/DreamInterpreter/openapi.yaml and DreamInterpreter/paths/__init__.py do not match. Load the later.
/root/OpenAgents-main/real_agents/plugins_agent/plugins/XWeather/openapi.yaml and XWeather/paths/__init__.py do not match. Load the later.
100%|███████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 17.99it/s]
Error: Failed to make the request MAPS: HTTPSConnectionPool(host='[smoothplugins.com](http://smoothplugins.com/)', port=443): Max retries exceeded with url: /img/plugin_logos2/maps1.png (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)')))

**Comment by yuantony009** [comment]
added www will fix the error, like www.smoothplugins.com

**Comment by Timothyxxx** [comment]
Thanks for your advice, would you be interested in making a pull request to fix it?

**Comment by Timothyxxx** [comment]
@yuantony009

**Comment by deeomnjobs** [comment]
Has this bug been fixed? I have the same problem.

**Comment by deeomnjobs** [comment]
> 这个错误被修复了吗？我有同样的问题。

I referred to yuantong009 solution. Specific changes below:
real_agents/plugins_agent/plugins/maps/ai-plugin.json
Change the logo_url value to "https://www.smoothplugins.com/img/plugin_logos2/maps1.png"

**Comment by Timothyxxx** [comment]
Glad the problem is solved, would you like to make a pull request to solve it? Or I will do that myself.
