### ISSUE TITLE
I cannot complete the installation. I can help by asking the openagents demo about the errors.

### ISSUE THREAD

**Issue by Enogh** [xlang-ai/OpenAgents#93]
I experienced many errors during the installation. I wanted to get help from openagents itself. Actually, he guided me very well, but I had a limit problem. With my own api key, I need to be able to ask openagents about its installation steps, errors and information about itself.

**Comment by BlankCheng** [comment]
Hi, have you tried to input your own key at the online demo? We have this functionality by clicking your account avatar at the "bottom-left" of the page.
