### ISSUE TITLE
Do those plugins in the data agent support running locally? 

### ISSUE THREAD

**Issue by deeomnjobs** [xlang-ai/OpenAgents#97]
Do those plugins in the data agent support running locally? Will data information and privacy be leaked when analyzing data?

**Comment by Timothyxxx** [comment]
OpenAgents can be used locally, you can totally run the demo by localhost, and use the local LLM to make sure the data information and privacy. For plugins, they will not use the data, just make some queries of questions and get information.

**Comment by deeomnjobs** [comment]
thx
