### ISSUE TITLE
FAQs about local deployment

### ISSUE THREAD

**Issue by BlankCheng** [xlang-ai/OpenAgents#99]
Here is a central FAQ for some commonly asked problems you might confront in local host. Thanks to all contributors for sharing their questions and solutions!

**Q: Frontend npm run failed.**
A: Firstly, we've removed some incompatible packages now, you might pull the latest version and try again. Second, please first try checking the node and npm versions. The node 18.7.0, npm 8.15.0 or node 21.0.0 + npm 10.2.0 pair work for now.

**Q: Docker host raises "backend overload".**
A: It is an issue of auto plugin selection install, and already been fixed in PR #98. Please try the latest dockerfile and code.

**Q: Docker parameter config.**
A: Some environmental parameters are personalized according to your env. Please check [README docker deploy](https://github.com/xlang-ai/OpenAgents#docker) to follow the detailed parameters for the docker config before building.

**Q: Python 3.11 raises "ValueError: 'not' is not a valid parameter name".**
A: It's a conflict between python and pydantic version. You can update pydantic version (1.10.2) according to [this issue](https://github.com/freqtrade/freqtrade/issues/7541).

**Q: Where is kaggle.json?**
A: You should sign up to Kaggle first and download your own API key file. Next, placing it as `~/.kaggle/kaggle.json` should let the app find it.

**Q: Flask stuck after loading all the plugins.**
A: In docker, it needs more time to start the application. If it takes a long time, please check if you have internet access to external websites especially when you are in cn because some plugin APIs might require it.

**Q: Web UI is running in localhost, but the response is stuck.**
A: Empirically it is mostly likely a proxy issue. Please check if you have internet access to external websites especially when you are in cn because LLM API calls require it.

**Q: Where is the "xlang-code-interpreter" code? Where is the user system code?**
A: We didn't release these parts because they are not relevant to the core of this open-source project and thus a bit tedious to put here. However, we upload the "xlang-code-interpreter" on dockerhub for anyone to execute python code in sandbox safely. You can see details [here](https://github.com/xlang-ai/OpenAgents/tree/main/backend).

**Q: How to contribute to this repo?**
A: We sincerely welcome all contributors to join. We can improve and maintain OpenAgents together! You might want to take a look at the [CONTRIBUTING](https://github.com/xlang-ai/OpenAgents/blob/main/CONTRIBUTING.md) and start your journey!

The issue will be kept updated!🔥

**Comment by zhaozhong** [comment]
How to change system language(i18n)? I tried http://localhost:3000/zh and nothing happened.
And in next-i18next.config I set defaultLocale: 'zh', it's not working too.

**Comment by 0769ljy** [comment]
hello,i try to run flask run -p 8080 ，but the following problems occur .  i can't visit the resource on the browser
Error: Failed to make the request JOBSEARCH: HTTPSConnectionPool(host='jobsearch.vencio.de', port=443): Max retries exceeded with url: /logo.png (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7efba110e4d0>: Failed to resolve 'jobsearch.vencio.de' ([Errno -2] Name or service not known)"))
Error: Failed to make the request SHOW_ME: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error: Failed to make the request MAPS: 403 Client Error: Forbidden for url: https://www.smoothplugins.com/img/plugin_logos2/maps1.png

**Comment by HungryFlo** [comment]
> hello,i try to run flask run -p 8080 ，but the following problems occur . i can't visit the resource on the browser Error: Failed to make the request JOBSEARCH: HTTPSConnectionPool(host='jobsearch.vencio.de', port=443): Max retries exceeded with url: /logo.png (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7efba110e4d0>: Failed to resolve 'jobsearch.vencio.de' ([Errno -2] Name or service not known)")) Error: Failed to make the request SHOW_ME: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) Error: Failed to make the request MAPS: 403 Client Error: Forbidden for url: https://www.smoothplugins.com/img/plugin_logos2/maps1.png

Same issue!

**Comment by 0769ljy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
